url.rewrite = (
    "^/wp-admin/$" => "$0"
)
url.rewrite-if-not-file = (
    "^/wp-json/(.*?)$" => "/index.php/wp-json/$1",
    "^/keyword/([A-Za-z_0-9\-]+)/?$" => "/index.php?keyword=$1",
    "^/.*?(\?.*)?$" => "/index.php$1"
)
